{% set name = "coverage-fixpaths" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0790d81fe2e77c494c8bf86e5fc9f9229b00c27ceaa3e0073e6404d49e4a79a4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - coverage-fixpaths = coveragefixpaths.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - coveragefixpaths
  commands:
    - coverage-fixpaths --help

about:
  home: https://github.com/omegacen/coverage-fixpaths
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: A small CLI tool that automatically fixes paths in Cobertura coverage reports

extra:
  recipe-maintainers:
    - teake
